### ISSUE TITLE
[Bug]: using dashboard restart cause crash

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#110]
### Describe the bug

restart via dashboard

### Jellyfin installation method

Dcoker

### Operating System

Docker

### Support Bundle

-

### Jellyfin logs
```
[2024-04-12 11:24:20.061 +02:00] [INF] [17] Main: Kestrel is listening on "127.0.0.1"
[2024-04-12 11:24:20.061 +02:00] [INF] [17] Main: Kestrel is listening on "172.21.0.2"
[2024-04-12 11:24:20.067 +02:00] [ERR] [17] Microsoft.Extensions.Hosting.Internal.Host: Hosting failed to start
System.InvalidOperationException: There was an error generating the XML document.
 ---> System.InvalidCastException: [A]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration cannot be cast to [B]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration. Type A originates from 'ConfusedPolarBear.Plugin.IntroSkipper, Version=0.2.0.1, Culture=neutral, PublicKeyToken=null' in the context '"" Emby.Server.Implementations.Plugins.PluginLoadContext #371' at location '/config/plugins/Intro Skipper_0.2.0.1/ConfusedPolarBear.Plugin.IntroSkipper.dll'. Type B originates from 'ConfusedPolarBear.Plugin.IntroSkipper, Version=0.2.0.1, Culture=neutral, PublicKeyToken=null' in the context '"" Emby.Server.Implementations.Plugins.PluginLoadContext #1' at location '/config/plugins/Intro Skipper_0.2.0.1/ConfusedPolarBear.Plugin.IntroSkipper.dll'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPluginConfiguration.Write6_PluginConfiguration(Object o)
   at InvokeStub_XmlSerializationWriterPluginConfiguration.Write6_PluginConfiguration(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToStream(Object obj, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at MediaBrowser.Common.Plugins.BasePlugin`1.SaveConfiguration(TConfigurationType config)
   at MediaBrowser.Common.Plugins.BasePlugin`1.LoadConfiguration()
   at MediaBrowser.Common.Plugins.BasePlugin`1.get_Configuration()
   at ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip.AutoSkipChanged(Object sender, EventArgs e)
   at ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-04-12 11:24:20.067 +02:00] [ERR] [17] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[2024-04-12 11:24:20.067 +02:00] [FTL] [17] Main: Error while starting server
System.InvalidOperationException: There was an error generating the XML document.
 ---> System.InvalidCastException: [A]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration cannot be cast to [B]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration. Type A originates from 'ConfusedPolarBear.Plugin.IntroSkipper, Version=0.2.0.1, Culture=neutral, PublicKeyToken=null' in the context '"" Emby.Server.Implementations.Plugins.PluginLoadContext #371' at location '/config/plugins/Intro Skipper_0.2.0.1/ConfusedPolarBear.Plugin.IntroSkipper.dll'. Type B originates from 'ConfusedPolarBear.Plugin.IntroSkipper, Version=0.2.0.1, Culture=neutral, PublicKeyToken=null' in the context '"" Emby.Server.Implementations.Plugins.PluginLoadContext #1' at location '/config/plugins/Intro Skipper_0.2.0.1/ConfusedPolarBear.Plugin.IntroSkipper.dll'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPluginConfiguration.Write6_PluginConfiguration(Object o)
   at InvokeStub_XmlSerializationWriterPluginConfiguration.Write6_PluginConfiguration(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToStream(Object obj, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at MediaBrowser.Common.Plugins.BasePlugin`1.SaveConfiguration(TConfigurationType config)
   at MediaBrowser.Common.Plugins.BasePlugin`1.LoadConfiguration()
   at MediaBrowser.Common.Plugins.BasePlugin`1.get_Configuration()
   at ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip.AutoSkipChanged(Object sender, EventArgs e)
   at ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-04-12 11:24:20.067 +02:00] [INF] [17] Main: Running query planner optimizations in the database... This might take a while
```

**Comment by jumoog** [comment]
The error message points out that `[A]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration` cannot be cast to `[B]ConfusedPolarBear.Plugin.IntroSkipper.Configuration.PluginConfiguration`. The types are identical, but they're being loaded from different contexts. This might be due to the way the assembly is loaded or how types are resolved within your application.

**Comment by jumoog** [comment]
thats cause the problem https://github.com/jumoog/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/Entrypoint.cs#L73

**Comment by rlauuzo** [comment]
The Dashboard restart function is not working in versions 2.0.0 and 2.0.1. for me.

```
[2024-04-12 10:55:42.531 +00:00] [INF] [15] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-04-12 10:55:42.531 +00:00] [INF] [15] Emby.Server.Implementations.ApplicationHost: Disposing "PluginManager"
[2024-04-12 10:55:42.532 +00:00] [INF] [15] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/cache"
[2024-04-12 10:55:42.532 +00:00] [FTL] [15] Main: Error while starting server
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
```

**Comment by jumoog** [comment]
AutoSkip Part is fixed

**Comment by rlauuzo** [comment]
Dont you also need add

`Plugin.Instance!.AutoSkipChanged -= AutoSkipChanged;`

here in AutoSkip.cs?
https://github.com/jumoog/intro-skipper/blob/06939ff3307c117266b7005045aab37ff677ef26/ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs#L232

**Comment by jumoog** [comment]
maybe.. it looks like there is a problem wiht Disposing the plugin

**Comment by jumoog** [comment]
All external plugins are affected!

**Comment by jumoog** [comment]
tracking issue here: https://github.com/jellyfin/jellyfin/issues/11349

**Comment by jumoog** [comment]
fix got merged

**Comment by jumoog** [comment]
`2024041505` and newer have the fix
