### ISSUE TITLE
[Bug]: Detection job fails if same folder is used multiple times in different libraries

### ISSUE THREAD

**Issue by Baine** [jumoog/intro-skipper#146]
### Describe the bug

I've got a library, that's combing the folders of 3 others (I've removed library scan enqueues of unrelated libraries)
"Anime-Gesamt" has the folders of "Anime-GerDub", "Anime-GerSub" and "Anime-Other"
When "Anime-Gesamt" is set up as library the detection fails after enqueuing the items, complaining that a job with that ID has already been added.
I've removed "Anime-Gesamt" as Library, and the detection job is processing as it should.

2 Support Bundles are attached
First with "Anime-Gesamt" not present, 2nd with "Anime-Gesamt" present.

### Jellyfin installation method

Docker

### Container image and tag

ghcr.io/hotio/jellyfin

### Operating System

Ubuntu 22.04.4 LTS

### Support Bundle

```shell
Combined Library removed

* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 46470 episodes, 4458 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

```shell
Combined Library recreated

* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 87721 episodes, 3439 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

### Jellyfin logs

```shell
[2024-05-08 06:57:05.125 +02:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Credits" Failed after 0 minute(s) and 4 seconds
[2024-05-08 06:57:05.125 +02:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-05-08 06:57:08.838 +02:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Detect Introductions"
[2024-05-08 06:57:09.009 +02:00] [INF] [20] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Anime-Gesamt"
[2024-05-08 06:57:11.002 +02:00] [INF] [20] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Anime-Other"
[2024-05-08 06:57:11.204 +02:00] [INF] [20] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Anime-GerSub"
[2024-05-08 06:57:12.292 +02:00] [INF] [20] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Anime-GerDub"
[2024-05-08 06:57:13.358 +02:00] [INF] [20] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntroductionsTask: Analyzing 6 files from "Anime1" season 1
[2024-05-08 06:57:13.358 +02:00] [INF] [24] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntroductionsTask: Analyzing 6 files from "Anime2" season 1
[2024-05-08 06:57:13.360 +02:00] [ERR] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: 6b6e65b7-7b01-3e57-72b5-c2c9388a8029) (An item with the same key has already been added. Key: c04c8e52-6db7-fddc-7f5d-6c057e6be7fc)
 ---> System.ArgumentException: An item with the same key has already been added. Key: 6b6e65b7-7b01-3e57-72b5-c2c9388a8029
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ConfusedPolarBear.Plugin.IntroSkipper.ChapterAnalyzer.AnalyzeMediaFiles(ReadOnlyCollection`1 analysisQueue, AnalysisMode mode, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(ReadOnlyCollection`1 items, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.<>c__DisplayClass5_0.<AnalyzeItems>b__0(KeyValuePair`2 season)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntroductionsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
 ---> (Inner Exception #1) System.ArgumentException: An item with the same key has already been added. Key: c04c8e52-6db7-fddc-7f5d-6c057e6be7fc
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ConfusedPolarBear.Plugin.IntroSkipper.ChapterAnalyzer.AnalyzeMediaFiles(ReadOnlyCollection`1 analysisQueue, AnalysisMode mode, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(ReadOnlyCollection`1 items, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.<>c__DisplayClass5_0.<AnalyzeItems>b__0(KeyValuePair`2 season)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by jumoog** [comment]
How did you create your "Combined Library"? Because you have the same episode `6b6e65b7-7b01-3e57-72b5-c2c9388a8029` twice in your library.

**Comment by Baine** [comment]
see below for the combined library
![image](https://github.com/jumoog/intro-skipper/assets/6566469/7baac347-ee72-48ea-ab4a-dd62c4719183)

and this is for one of the others using the folder
![image](https://github.com/jumoog/intro-skipper/assets/6566469/c0f1c12e-db46-4e66-9418-078ae19d9d0d)
(apologies for the german in that snips; "Verzeichnisse" = "Directories"; hope it's understandable)

**Comment by rlauuzo** [comment]
Could you please test if this https://github.com/jumoog/intro-skipper/actions/runs/9000490094?pr=147 resolves the issue for you? Simply replace the DLL in the plugin folder, then restart Jellyfin to apply the update.

**Comment by Baine** [comment]
yep, that did resolve this issue.

thank you!

**Comment by jumoog** [comment]
> see below for the combined library ![image](https://private-user-images.githubusercontent.com/6566469/328814608-7baac347-ee72-48ea-ab4a-dd62c4719183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjkxNjMsIm5iZiI6MTcxNTE2ODg2MywicGF0aCI6Ii82NTY2NDY5LzMyODgxNDYwOC03YmFhYzM0Ny1lZTcyLTQ4ZWEtYWI0YS1kZDYyYzQ3MTkxODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTE0NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZkOWI1ZWE5M2U5OTNiOTQ1NzYwN2YzYWNjMTM5OGM2MDc0ZjVkMmM2NmIzZDZmMDU0NTI1MDhmZTgyMWI5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JZOPlHRHBG_g_WaSF_UKZJwwXSRdnSNrvOIPtegdPac)
> 
> and this is for one of the others using the folder ![image](https://private-user-images.githubusercontent.com/6566469/328814918-c0f1c12e-db46-4e66-9418-078ae19d9d0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjkxNjMsIm5iZiI6MTcxNTE2ODg2MywicGF0aCI6Ii82NTY2NDY5LzMyODgxNDkxOC1jMGYxYzEyZS1kYjQ2LTRlNjYtOTQxOC0wNzhhZTE5ZDlkMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTE0NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU3NWRhNWI1MjE3OWZlOTk3NTEzM2ZjMWRjZjJlYTM4NTA1ODdhMGJhNTM3YThkNjc4NmM1ZDYyMDA0ZWEwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EZbVj4CAdND1JGcGWMtncXx5ZBLSMBB4PHVLo6zZw34) (apologies for the german in that snips; "Verzeichnisse" = "Directories"; hope it's understandable)
> 
> iirc jellyfin assigns the episode ids based on the folder they are in, and not based on the library

don't worry i'm from germany
