### ISSUE TITLE
[Bug]: detect intros and outros task always fails

### ISSUE THREAD

**Issue by drached** [jumoog/intro-skipper#151]
### Describe the bug

When i try to detect intros and outros the task always fails

### Jellyfin installation method

Docker

### Container image and tag

lscr.io/linuxserver/jellyfin:latest

### Operating System

Unraid 6.12.10

### Support Bundle

```shell
* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 14926 episodes, 505 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
```


### Jellyfin logs

```shell
[22:10:44] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Detect Intros and Credits
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library Anime
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library Serien
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library Filme
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library Collections
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Analyzing 8 files from .hack//Liminality season 1
[22:10:44] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Analyzing 6 files from .hack//Quantum season 1
[22:10:45] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Analyzing 52 files from .hack//ROOTS season 1
[22:10:45] [ERR] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: b16fbb5e-a045-2263-ee56-5f197cdb9585)
 ---> System.ArgumentException: An item with the same key has already been added. Key: b16fbb5e-a045-2263-ee56-5f197cdb9585
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ConfusedPolarBear.Plugin.IntroSkipper.ChapterAnalyzer.AnalyzeMediaFiles(ReadOnlyCollection`1 analysisQueue, AnalysisMode mode, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(ReadOnlyCollection`1 items, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.<>c__DisplayClass5_0.<AnalyzeItems>b__0(KeyValuePair`2 season)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by jumoog** [comment]
is already fixed see #146 we need a new release

**Comment by rlauuzo** [comment]
Test if the Preview Version resolves the issue. Simply replace the DLL in the plugin folder, then restart Jellyfin to apply the update. https://github.com/jumoog/intro-skipper/releases/tag/10.8%2Fpreview

**Comment by drached** [comment]
Thanks the Preview version seems to already fix the Problem
