### ISSUE TITLE
[Bug]: Introskip Scheduled Task Fails Instantly

### ISSUE THREAD

**Issue by xManvir** [jumoog/intro-skipper#161]
### Describe the bug

When I run the intro skip task, it fails instantly. When I restart the server, it runs but fails at some point.

### Jellyfin installation method

Docker

### Container image and tag

linuxserver/jellyfin:latest

### Operating System

Ubuntu 20.04

### Support Bundle

```shell
* Jellyfin version: 10.9.1
* Plugin version: 0.2.0+8f60bc2948ad
* Queue contents: 15 episodes, 1 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

```shell
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-13 18:00:51.448 -04:00] [INF] [104] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-13 18:00:51.779 -04:00] [INF] [43] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Automatic Task is Running and will be canceled.
[2024-05-13 18:00:51.779 -04:00] [ERR] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-13 18:00:51.779 -04:00] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-13 18:00:52.084 -04:00] [INF] [104] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Automatic Task is Running and will be canceled.
[2024-05-13 18:00:52.085 -04:00] [ERR] [104] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-13 18:00:52.085 -04:00] [INF] [104] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-13 18:00:52.293 -04:00] [ERR] [43] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "DELETE" "/ScheduledTasks/Running/60998e87762c85231d07856acaff039f".
System.InvalidOperationException: Cannot cancel a Task unless it is in the Running state.
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.Cancel()
   at Emby.Server.Implementations.ScheduledTasks.TaskManager.Cancel(IScheduledTaskWorker task)
   at Jellyfin.Api.Controllers.ScheduledTasksController.StopTask(String taskId)
   at lambda_method2740(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-05-13 18:00:56.785 -04:00] [INF] [3] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosTask: Automatic Task is Running and will be canceled.
[2024-05-13 18:00:56.785 -04:00] [ERR] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-13 18:00:56.785 -04:00] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros" Failed after 0 minute(s) and 0 seconds
[2024-05-13 18:00:58.354 -04:00] [INF] [43] ConfusedPolarBear.Plugin.IntroSkipper.DetectCreditsTask: Automatic Task is Running and will be canceled.
[2024-05-13 18:00:58.355 -04:00] [ERR] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-13 18:00:58.355 -04:00] [INF] [43] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Credits" Failed after 0 minute(s) and 0 seconds
```

**Comment by rlauuzo** [comment]
Could you please check if https://github.com/jumoog/intro-skipper/actions/runs/9075240227?pr=163 resolves the issue for you? Simply replace the DLL in the plugin folder, then restart Jellyfin to apply the update.

**Comment by rohitghali** [comment]
> Could you please check if https://github.com/jumoog/intro-skipper/actions/runs/9096118959?pr=163 resolves the issue for you? Simply replace the DLL in the plugin folder, then restart Jellyfin to apply the update.

I tried this. Didn't work. Here's my log...

`[2024-05-15 11:12:22.109 -04:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-15 11:12:22.715 -04:00] [INF] [36] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Automatic Task is Running and will be canceled.
[2024-05-15 11:12:22.721 -04:00] [ERR] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-15 11:12:22.728 -04:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
`

**Comment by AbandonedCart** [comment]
Looks like https://github.com/jumoog/intro-skipper/pull/163 is addressing that issue.

**Comment by Bretterteig** [comment]
FYI
Had the same issue. PR .ddl fixed it for me.

**Comment by rohitghali** [comment]
> > > Could you please check if https://github.com/jumoog/intro-skipper/actions/runs/9096118959?pr=163 resolves the issue for you? Simply replace the DLL in the plugin folder, then restart Jellyfin to apply the update.
> > 
> > 
> > I tried this. Didn't work. Here's my log...
> > `[2024-05-15 11:12:22.109 -04:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds [2024-05-15 11:12:22.715 -04:00] [INF] [36] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Automatic Task is Running and will be canceled. [2024-05-15 11:12:22.721 -04:00] [ERR] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task System.ObjectDisposedException: The CancellationTokenSource has been disposed. at System.Threading.CancellationTokenSource.Cancel() at ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint.CancelAutomaticTask(CancellationToken cancellationToken) at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress1 progress, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) [2024-05-15 11:12:22.728 -04:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds `
> 
> Have you restarted Jellyfin after replacing the DLL?

I did. Jellyfin doesn't allow to replace the file while running. So, had to stop jellyfin, replace the file and then start again. So it definitely is restarted.

**Comment by rohitghali** [comment]
> can you try with the new version?

Still not working. Not sure what the issue is or even if it is related to this. Here's the log.

`[2024-05-16 14:07:19.877 -04:00] [ERR] [57] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Error validating encoder
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\CustomPrograms\ffmpeg\bin' with working directory 'C:\Program Files\Jellyfin\Server'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[2024-05-16 14:07:19.883 -04:00] [WRN] [57] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: "C:\CustomPrograms\ffmpeg\bin"
[2024-05-16 14:07:19.887 -04:00] [INF] [57] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: ""
[2024-05-16 14:07:19.891 -04:00] [INF] [57] Emby.Server.Implementations.ApplicationHost: ServerId: "31cd679a21cf4ee68163955bd37630d2"
[2024-05-16 14:07:19.895 -04:00] [INF] [57] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-05-16 14:07:19.897 -04:00] [INF] [57] Main: Startup complete 0:00:06.0539772
[2024-05-16 14:07:22.899 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:23.540 -04:00] [INF] [57] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:48.539 -04:00] [INF] [42] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-05-16 14:07:54.957 -04:00] [INF] [31] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:54.964 -04:00] [ERR] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:54.968 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:55.852 -04:00] [INF] [42] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:55.855 -04:00] [ERR] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:55.861 -04:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:56.281 -04:00] [INF] [31] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:56.284 -04:00] [ERR] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:56.290 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:56.468 -04:00] [INF] [32] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:56.471 -04:00] [ERR] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:56.476 -04:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:56.648 -04:00] [INF] [31] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:56.652 -04:00] [ERR] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:56.657 -04:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:07:57.020 -04:00] [INF] [42] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-05-16 14:07:57.024 -04:00] [ERR] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: Analysis terminated! Chromaprint is not enabled in the current ffmpeg. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade to version 10.8.0 or newer.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-05-16 14:07:57.027 -04:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
[2024-05-16 14:08:19.867 -04:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds`

**Comment by jumoog** [comment]
I tries to open ffmpeg from `C:\CustomPrograms\ffmpeg\bin` and that fails. For it looks like the ffmpeg path is wrong.

**Comment by AbandonedCart** [comment]
If you need a custom path, check under the [Mac instructions](https://github.com/jumoog/intro-skipper#installation-macos) for how to set up their configuration file. They made a really convoluted process out of a simple ui entry.

**Comment by rohitghali** [comment]
> It tries to open ffmpeg from `C:\CustomPrograms\ffmpeg\bin` and that fails. For me it looks like the ffmpeg path is wrong.

Yeah. Just noticed it in the logs. Weird. Nothing changed. Only change is server update to 10.9. And the ffmpeg binary exists in that path. I'll dig deeper into what's happening. Thanks.
