### ISSUE TITLE
10.9 autoskip funktion isn't working (skip button is issue #104)

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#168]
It didn't worked yesterday. 

This issue is only about autoskip.. if can't see the skip button in the webversion check  https://github.com/jumoog/intro-skipper/issues/104

If you can't see this buttons in the dashboard:

![grafik](https://github.com/jumoog/intro-skipper/assets/5268791/e3a5b24c-5107-496a-ac29-2e84a42d3cb7)

autoskip won't work either.

**Comment by jumoog** [comment]
Today it works perfectly. I think it is a jellyfin bug the playback progress is not being reported correctly.

**Comment by FuZion45** [comment]
hi, it doesn't work for me, no auto skipper or skip button, in the log I don't see any apparent error, it analyzes the libraries well however, I should never have done the new jellyfin update, because before everything worked very well

**Comment by Chat-mots** [comment]
I have recently update to 10.9.1, intro slipper 2.0.4. Auto skip works fine but there is no skip intro button displaying :(

**Comment by AbandonedCart** [comment]
> I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(

That should be resolved in the next update/

**Comment by FuZion45** [comment]
> I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(

I was able to get the skippe auto to work last night, this morning when I got up it no longer works, the plugin seems not stable it seems

**Comment by jumoog** [comment]
> > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> 
> I was able to get the skippe auto to work last night, this morning when I got up it no longer works, the plugin seems not stable it seems

I noticed the same problem, after some time the client no longer reports the correct play position.

**Comment by FuZion45** [comment]
> > > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> > 
> > 
> > I was able to get the skippe auto to work last night, this morning when I got up it no longer works, the plugin seems not stable it seems
> 
> I noticed the same problem. after some time the client does not report back the correct play position. But the plugin needs the correct play position to skip the intro.

ok, is there a solution to fix this? or a future update of the plugin in the coming days?

**Comment by jumoog** [comment]
> Working for 10.9.2.
> 
> On Android tv it's now auto playing next episode, before the next up screen would show/

i'll restore the old funktion

**Comment by jumoog** [comment]
````
2024-05-18T18:18:49.870191253Z [20:18:49] [ERR] [44] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:49.870219822Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:49.870223482Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:49.870226562Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:49.870229652Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:18:50.161235517Z [20:18:50] [ERR] [44] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:50.161259807Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:50.161262077Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:50.161264547Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:50.161266497Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:18:50.870710330Z [20:18:50] [ERR] [64] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:50.870727799Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:50.870730579Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:50.870732999Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:50.870735449Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:18:51.161833603Z [20:18:51] [ERR] [64] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:51.161868232Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:51.161873112Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:51.161877582Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:51.161881572Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:18:51.869047618Z [20:18:51] [ERR] [64] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:51.869078278Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:51.869093537Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:51.869095867Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:51.869097927Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
2024-05-18T18:18:52.160100883Z [20:18:52] [ERR] [64] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
2024-05-18T18:18:52.160139252Z System.ObjectDisposedException: Cannot access a disposed object.
2024-05-18T18:18:52.160145592Z Object name: 'Emby.Server.Implementations.Session.SessionManager'.
2024-05-18T18:18:52.160151451Z    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
2024-05-18T18:18:52.160157561Z    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
````

**Comment by jumoog** [comment]
Its a Jellyfin bug

**Comment by jumoog** [comment]
> > Working for 10.9.2.
> > On Android tv it's now auto playing next episode, before the next up screen would show/
> 
> i'll restore the old funktion

it's in `v0.2.0.5`

**Comment by Chat-mots** [comment]
Solved my issue on windows. 
For those who are confused if the plugin has enough permissions, activate the full debug logs and be sure introskipper has the permission to modify html ! @FuZion45

**Comment by AbandonedCart** [comment]
> Any additional steps required for a docker env?

> How would you modify permissions for introskipper for docker?

See https://github.com/jumoog/intro-skipper/issues/104

**Comment by jumoog** [comment]
The seek command was sent but I don't see a message in the websocket

```
2024-05-20T11:24:07.620422975Z [13:24:07] [INF] [47] ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip: Playback position is 357, intro runs from 354.68699999999995 to 381.88939999999997

2024-05-20T11:24:07.620486503Z [13:24:07] [INF] [47] ConfusedPolarBear.Plugin.IntroSkipper.AutoSkip: Sending seek command to TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI2LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI2LjB8MTcxNjIwMjgwMzQ3Ng11
```

![grafik](https://github.com/jumoog/intro-skipper/assets/5268791/9c9972fa-74eb-4a91-9396-16e1db0b4b72)

**Comment by jumoog** [comment]
When this happens, I can't control the session from the Jellyfin dashboard.

**Comment by jumoog** [comment]
I have opened an issue here: https://github.com/jellyfin/jellyfin/issues/11755

**Comment by saydo17** [comment]
Hi, I finally got mine working again.  I had to Erase all introduction/end credits timestamps.  I think something got messed up with the cache when I updated.

**Comment by rlauuzo** [comment]
I had the same problem! A bunch of my intro timestamps were showing as IntroEnd 0, making them invalid.

**Comment by ramonskie** [comment]
@saydo17 how can you do the cleanup?

**Comment by saydo17** [comment]
> @saydo17 how can you do the cleanup?

Under the Advanced section of the config, open the Manage Fingerprints section. There are two buttons at the bottom.  I ran the detect intros and credits task again after.

**Comment by saydo17** [comment]
> I had the same problem! A bunch of my intro timestamps were showing as IntroEnd 0, making them invalid.

Exact same thing for me!

**Comment by jumoog** [comment]
This may be related to the changes made to https://github.com/jumoog/intro-skipper/commit/03af05c3c6fd7090d8ad851924e8717d31b2cd26. I also had to adjust the timing of the unit tests.

**Comment by rlauuzo** [comment]
https://github.com/jumoog/intro-skipper/pull/177 maybe fixes it

**Comment by jumoog** [comment]
Okay i run the Android TV App `v0.16.10` in the Android TV Emulator and i can't controll the Session from the Jellyfin Dashboard. I don't see the send Messages.

**Comment by jumoog** [comment]
As a plugin, we can't do more than send the command to seek. Unfortunately, we cannot do anything about whether it reaches the client.

**Comment by Ruchamimi** [comment]
> > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> 
> That should be resolved in the next update/



> > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> 
> That should be resolved in the next update/



> > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> 
> That should be resolved in the next update/

I have just updated JF to 10.9.3 and intro skipper to 2.0.8 and I still don't have the skip button on web. Button works well on windows client and findroid though, as well as auto skip. Is it a known issue or due to permissions on my end (apt install on raspberry pi 4)

**Comment by jumoog** [comment]
This is probably a permissions error: https://github.com/jumoog/intro-skipper/issues/104

**Comment by jumoog** [comment]
> > > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> > 
> > 
> > That should be resolved in the next update/
> 
> > > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> > 
> > 
> > That should be resolved in the next update/
> 
> > > I have recently updated to 10.9.1, intro skipper to 2.0.4. Auto skip works fine but there is no skip intro button displayed. :(
> > 
> > 
> > That should be resolved in the next update/
> 
> I have just updated JF to 10.9.3 and intro skipper to 2.0.8 and I still don't have the skip button on web. Button works well on windows client and findroid though, as well as auto skip. Is it a known issue or due to permissions on my end (apt install on raspberry pi 4)

This is probably a permissions error: https://github.com/jumoog/intro-skipper/issues/104

**Comment by jumoog** [comment]
I'll make that clear.

**Comment by Ruchamimi** [comment]
> This is probably a permissions error: #104

Sorry for being confused about that. /usr/share/jellyfin/web/index.html belongs to root.
For which should I change ?

**Comment by rlauuzo** [comment]
That depends on your installation method. Are you using Docker or a native installation?

**Comment by Ruchamimi** [comment]
Native installation

**Comment by rlauuzo** [comment]
On Ubuntu/Debian systems, change to use "jellyfin" as the user:

` chown jellyfin /usr/share/jellyfin/web/index.html`

**Comment by Ruchamimi** [comment]
Did it and it works great ! Thank you sir.

**Comment by jumoog** [comment]
I currently have no more problems with androidtv `0.16.11` and jellyfin `10.9.6`

**Comment by Brramble** [comment]
since 10.9.6, I also have not had any issues with android TV clients (0.16.11). Only the unsupported TV clients remain ontop of the web os. Hopefully Jellyfin have plans for this websocket support moving forward.

**Comment by ceruleanight** [comment]
it's not skipping for me either on 0.16.11 and 10.9.6

**Comment by jumoog** [comment]
> I am seeing that a WS was opened but then is closed. This is a bug that gets fixed by an update then unfixed with another.
> 
> ```
>  error receiving data: "The remote party closed the WebSocket connection without completing the close handshake.
>  [INF] WS ":::IP" closed
> WS "::IP" request
> ```

Okay but thats a Jellyfin error

**Comment by AbandonedCart** [comment]
>  best it's reported here then new issues getting open because people think it's the plugin

Wishful thinking...

**Comment by Dnkhatri** [comment]
The auto skip seems to be working for both intro and credits n the latest Android tv beta

**Comment by AbandonedCart** [comment]
Isn't the PR for this still in draft?

**Comment by jumoog** [comment]
> Isn't the PR for this still in draft?

PR #208 changes the current behavior from sending to every client to sending to selected clients.

**Comment by AbandonedCart** [comment]
> @AbandonedCart There is already an auto skip option for all clients, I think that's what @Dnkhatri Is talking about.

... Really fighting the urge to say "oh really? I had no idea." lol. The questions was because it was my understanding that always worked and what was currently being discussed was making an option to automatically enable it for certain clients.

> PR #208 changes the current behavior from sending to every client to sending to selected clients.

I didn't realize at the time it was replacing that feature. It should definitely be two separate items. There are a **lot** of people that will have clients perfectly capable of pressing the button that still want to skip automatically.

**Comment by jumoog** [comment]
> I didn't realize at the time it was replacing that feature. ~It should definitely be two separate items~ There should definitely be a bulk option labeled " All Clients". There are a **lot** of people that will have clients perfectly capable of pressing the button that still want to skip automatically.

Yes, that was the plan. If you uncheck `all`, you have to choose.

**Comment by AbandonedCart** [comment]
I unpinned the issue since it appears to be either working already or just waiting on the PR. This should avoid confusion with the similarly named issue about fixing permissions.
