### ISSUE TITLE
[Bug]: Plugin failed to run

### ISSUE THREAD

**Issue by karserasl** [jumoog/intro-skipper#176]
### Describe the bug

Plugin failed to run on startup

### Jellyfin installation method

Native

### Operating System

Debian 12

### Support Bundle

```shell
Cant add this since the plugin doesnt even run
```

### Jellyfin logs

```shell
[2024-05-21 09:01:05.453 +03:00] [ERR] Error creating "ConfusedPolarBear.Plugin.IntroSkipper.Plugin"
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at ConfusedPolarBear.Plugin.IntroSkipper.XmlSerializationHelper.MigrateXML(String filePath)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
[2024-05-21 09:01:05.459 +03:00] [INF] Plugin "/mnt/userdata/jellyfin/plugins/Intro Skipper_0.2.0.6" has been disabled.
```

**Comment by jumoog** [comment]
What have you done? Have you upgraded from `10.8.x` and replaced `ConfusedPolarBear/intro-skipper` with mine?

**Comment by karserasl** [comment]
I upgraded to latest jellyfin

i replaced ConfusedPolarBear's with yours, and got the error.

Then went and deleted the folders in plugins, delete the repos and readded them

Still getting that

**Comment by bwaddington** [comment]
Server version 10.9.1
Web version 10.9.1
Build version 10.9.1

had to rolback to

Intro Skipper0.2.0.4
Status Active

working again now

keep gettin not supported for

Intro Skipper0.2.0.5
Status NotSupported

Intro Skipper0.2.0.6
Status NotSupported

**Comment by karserasl** [comment]
> Server version 10.9.1 Web version 10.9.1 Build version 10.9.1
> 
> had to rolback to
> 
> Intro Skipper0.2.0.4 Status Active
> 
> working again now
> 
> keep gettin not supported for
> 
> Intro Skipper0.2.0.5 Status NotSupported
> 
> Intro Skipper0.2.0.6 Status NotSupported

Thats probably because the latest version of jellyfin is 10.9.2

**Comment by jumoog** [comment]
Do you have the `/config/plugins/intros' folder? Not sure where it is for non-Docker installations?

**Comment by karserasl** [comment]
Ok found the problem

it was something in this path: `jellyfin/data/introskipper` 
i delete that and its working..

Thanks

**Comment by AbandonedCart** [comment]
I'm not 100% confident in that mess to move the cache again, so I may have messed something up.

**Comment by jumoog** [comment]
I tested all possible cases

**Comment by bigboigahoy** [comment]
I seem to be having the same issue. I uninstalled the old ConfusedPolarBear version, then installed the latest from this fork. I don't seem to have this directory `jellyfin/data/introskipper` and I am using Docker.
