### ISSUE TITLE
[Bug]: Access to the path '/usr/share/jellyfin/web/index.html' is denied.

### ISSUE THREAD

**Issue by GuyKh** [jumoog/intro-skipper#180]
### Describe the bug

Using `linuxserver/jellyfin`,
Downloaded the relevant UI package and extracted to `.../jellyfin/jellyfin-web/dist...`

This is my docker-compose.yaml settings:
```
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      #- UID=${PUID} # The UID to run emby as (default: 2)
      #- GID=${PGID} # The GID to run emby as (default 2)
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - ${HOME}/docker/jellyfin/config:/config # Configuration directory
      - ${HOME}/docker/jellyfin/cache:/cache
      - ${HOME}/docker/jellyfin/fonts:/fonts
      - ${HOME}/docker/jellyfin/jellyfin-web/dist:/usr/share/jellyfin/web:ro
```

No matter if the files are owned by root (`sudo chown root:root -R ${HOME}/docker/jellyfin/jellyfin-web/dist`) or any other user, I still get the same error;

Tried adding and removing the UID and GID (user `root` - so `1000` in both cases) - still the same happening.

What am I doing wrong?

### Jellyfin installation method

Docker

### Container image and tag

linuxserver/jellyfin:latest.

### Operating System

Ubuntu 24.04

### Support Bundle

```shell
* Jellyfin version: 10.9.2
* Plugin version: 0.2.0+9b2954f16d40
* Queue contents: 36 episodes, 8 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

```shell
[19:51:07] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.InjectSkipButton(String indexPath)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
Trailing option(s) found in the command: may be ignored.
[19:51:07] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Intro Skipper 0.2.0.7
```
```

**Comment by rlauuzo** [comment]
> Downloaded the relevant UI package and extracted to `.../jellyfin/jellyfin-web/dist...`

Please avoid doing that, and it should be removed. To make the skip button work, you have to run `docker exec -u root -it jellyfin chown abc /usr/share/jellyfin/web/index.html` or create a custom script for LinuxServer https://github.com/jumoog/intro-skipper/issues/104#issuecomment-2034919914.

**Comment by GuyKh** [comment]
Amazing! Thanks!!
