### ISSUE TITLE
[Bug]: The skip intro button is not appearing. (Windows 11)

### ISSUE THREAD

**Issue by renash2me** [jumoog/intro-skipper#210]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

The plugin scans all my libraries. On the playback timeline, the intro and credits markers appear, but the button does not show up.

I tried to follow the forum, the documentation, and other sources, but I couldn't find anything related to Jellyfin installed on a computer running Windows.

Can you help me?

### Jellyfin install method

Windows

### Container image/tag or Jellyfin version

10.9.7

### Operating System

Windows 11

### Support Bundle

```shell
* Jellyfin version: 10.9.7
* Plugin version: 0.2.0+6f127ca7bf58
* Queue contents: 354 episodes, 21 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13-win32 (GCC)
configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Find `index.html` in `C:\Program Files\Jellyfin\Server\jellyfin-web` and modify the permissions for your user to Full Control. Then restart Jellyfin.

**Comment by renash2me** [comment]
It worked! Thank you so much!

**Comment by zohebhynus** [comment]
Hey Guys,

I am running the Jellyfin server on my personal computer on Windows 10.

I tried the solution that 'rlauuzo' mentioned and it still doesn't work for me. I still get the permission error in the logs
```
[2024-08-03 13:04:11.302 -07:00] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try "changing the permissions of C:\Program Files\Jellyfin\Server\jellyfin-web\index.html" and restarting the server. Error: "System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Jellyfin\Server\jellyfin-web\index.html' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.InjectSkipButton(String indexPath)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)"
```

This is the permission page for `index.html`
![image](https://github.com/user-attachments/assets/e38c8374-00fd-4cfe-8e6a-c28fed47ba99)
To make sure I didn't miss anything, I provided full control to all groups.

I even tried adding
`<script src="configurationpage?name=skip-intro-button.js"></script>` directly to the index.html file and it didn't work.

Does anyone know what I am doing wrong?

P.S solving this `index.html` permissions issue will also resolve another issue with regards to this plugin (https://github.com/Namo2/InPlayerEpisodePreview) as well. Any help is appreciated.

**Comment by rlauuzo** [comment]
Have you restarted Jellyfin after changing the permissions?

**Comment by zohebhynus** [comment]
I did restart the Jellyfin server instance after changing the permissions. the logs were from the new instance. I should've mentioned that. My apologies.

It still doesn't work. :/

**Comment by rlauuzo** [comment]
I'm not sure what else could be causing the issue. Maybe try rebooting Windows and see if that resolves it?

**Comment by AbandonedCart** [comment]
Did you only change permissions to the index and not the entire folder?

**Comment by zohebhynus** [comment]
@AbandonedCart 
That fixed it. Now the logs shows that `index.html` has been updated correctly
```
[2024-08-04 12:07:41.570 -07:00] [INF] [1] Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Found client script injected in "C:\Program Files\Jellyfin\Server\jellyfin-web\index.html"
[2024-08-04 12:07:41.573 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "InPlayerEpisodePreview" "1.2.1.0"
[2024-08-04 12:07:41.742 -07:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Skip button already added
[2024-08-04 12:07:41.984 -07:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Intro Skipper" "0.2.0.12"
```

The skip button still does not show up, but I can look into debugging further and go through the other issues on github to figure out what the problem is.

Thanks for the help!
