### ISSUE TITLE
[Bug]: Cannot inject skip button in NixOS/nixpkgs

### ISSUE THREAD

**Issue by Waelwindows** [jumoog/intro-skipper#237]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

When jellyfin is ran from `nixpkgs`, its containing folder is inside the nix store which is read only and cannot be modified by the user. As such, the plugin fails to patch `index.html`. The proper method is to patch jellyfin in `nixpkgs` like https://github.com/ConfusedPolarBear/intro-skipper/issues/200 suggests. 

The problem is, since the patch is done dynamically in fork, there is no "direct" patch file that we can use in `nixpkgs` to patch/inject the skip button script during the build of jellyfin.

### Jellyfin install method

nixpkgs

### Container image/tag or Jellyfin version

jellyfin/jellyfin:10.9.7 (from nixpkgs commit `9f4128e00b0ae8ec65918efeba59db998750ead6`)

### Operating System

NixOS

### Support Bundle

```shell
* Jellyfin version: 10.9.7
* Plugin version: 0.2.0+a13733bdad67
* Queue contents: 876 episodes, 78 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.3.0 (GCC)
configuration: --disable-static --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --disable-static --enable-shared --enable-pic --disable-thumb --disable-small --enable-runtime-cpudetect --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/4whw8qh40gadr4i3mvhlfbwghivppmx8-jellyfin-ffmpeg-6.0.1-6-data/share/ffmpeg --enable-ffmpeg --enable-ffplay --enable-ffprobe --bindir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6-lib/lib --incdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-jellyfin-ffmpeg-6.0.1-6-doc/share/doc/ffmpeg --enable-alsa --enable-libaom --disable-appkit --enable-libass --disable-audiotoolbox --disable-avfoundation --enable-avisynth --enable-libbluray --enable-libbs2b --enable-bzlib --enable-libcaca --enable-libcelt --enable-chromaprint --enable-libcodec2 --disable-coreimage --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-libdav1d --enable-libdc1394 --enable-libdrm --disable-libfdk-aac --enable-ffnvcodec --enable-libflite --enable-fontconfig --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-iconv --enable-libjack --enable-libjxl --enable-ladspa --enable-lzma --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-nvdec --enable-nvenc --enable-openal --enable-opencl --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librtmp --enable-libsmbclient --enable-sdl2 --enable-libshaderc --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-librsvg --enable-libsvtav1 --disable-libtensorflow --enable-libtheora --enable-libv4l2 --enable-v4l2-m2m --enable-vaapi --enable-vdpau --disable-libvpl --disable-videotoolbox --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-vulkan --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm --enable-libxcb-xfixes --enable-xlib --enable-libxml2 --enable-libxvid --enable-libzimg --enable-zlib --enable-libzmq --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping --extra-version=Jellyfin --disable-ptx-compression
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

```shell
[2024-08-02 00:04:33.762 +03:00] [ERR] [38] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try "running `sudo chown jellyfin /nix/store/niy7hjffkfr7qfnx542gsppfl02v3ypb-jellyfin-web-10.9.7/share/jellyfin-web/index.html` (if this is a native installation)" and restarting the server. Error: "System.UnauthorizedAccessException: Access to the path '/nix/store/niy7hjffkfr7qfnx542gsppfl02v3ypb-jellyfin-web-10.9.7/share/jellyfin-web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.InjectSkipButton(String indexPath)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)"
```

**Comment by AbandonedCart** [comment]
Seems you need some variation of https://github.com/jumoog/intro-skipper#skip-button-is-not-visible

**Comment by jumoog** [comment]
ok this was the old diff: https://github.com/jellyfin/jellyfin-web/compare/v10.8.10...ConfusedPolarBear:jellyfin-web:intros.diff

There is no updated `jellyfin-web` fork with a built-in skip button. You have to inject the code at build time.

```html
<script src="configurationpage?name=skip-intro-button.js"></script>
```

**Comment by jumoog** [comment]
There are also no plans at the moment to have a `jellyfin-web` fork with built-in skip button.

**Comment by eyJhb** [comment]
I just tried this plugin on the latest version, and it seems like it just works out of the box, without any modifications to jellyfin-web. At least it works with the web player, jellyfin media player, an dthe TV app.

**Comment by jumoog** [comment]
Yes because there is official support

**Comment by AbandonedCart** [comment]
I deleted the mention in the other issue, since both were marked resolved over a year ago.

**Comment by eyJhb** [comment]
I'm really unsure why either of you would think anyone would come to the conclusion, that this has been fixed and is now officially supported by reading any of these issues. The other issue links to this, stating that the information should be kept in here.
This issue was "completed" with a `wontfix` tag, and no other information to it.

Based on that information, I'm quite certain that no one, except the ones that maybe fixed the issue, would come to the conclusion that it now works without any changes mention in both issues.

That's the reason that i:

1. Commented on both issues to indicate that it actually works great now.
2. Updated the linked wiki to indicate this as well.

**Comment by jumoog** [comment]
> I'm really unsure why either of you would think anyone would come to the conclusion, that this has been fixed and is now officially supported by reading any of these issues.

This problem doesn't occur in the latest version. It's related to Jellyfin version 10.9 and has nothing to do with the plugin. It's an issue with NixOS/nixpkgs. As mentioned, we don't provide a patch, so I picked the `wontfix` tag.

> I just tried this plugin on the latest version, and it seems like it just works out of the box, without any modifications to jellyfin-web. At least it works with the web player, jellyfin media player, an dthe TV app.

Yes, the average user will update to the latest version and won't encounter this problem.

**Comment by jumoog** [comment]
I update the status to `Close as not planned`

**Comment by eyJhb** [comment]
I merely posted this so others (like me), who found the issue would know that it isn't an issue anymore, and wouldn't try to patch their nixpkgs to make it work.

I was in doubt if it worked without any changes, and therefore I made this comment on the issue tracker, that even though this is closed as wontfix/not planned, this is a non-issue and it works without any changes.

I think maybe you both misunderstood my intentions with my comment, which was not to inform the maintainers of the project, but others like me. :)

**Comment by jumoog** [comment]
Ok thank you! I updated the text of the issue and added:

> [!IMPORTANT]  
> If this happens, update to the latest version of Jellyfin. A patch is no longer necessary.

**Comment by AbandonedCart** [comment]
I think my comment was also misunderstood. A closed issue is no longer updated once it is closed and the only reason to request it being opened again is typically when it is still an issue. However, you were not requesting that it be opened. You were commenting that it is no longer a valid issue and should remain closed. This tends to cause a lot of confusion about your actual intentions and for those that do stumble across the issue that is now active for some reason, especially when the topic is using a modified web client and everything else related to that has been marked obsolete.

I deleted the other issue because it was already noted that it was only an extension of this one and redirected back here, but adding more comments to direct it back here multiple times was simply spamming notifications for everyone involved.
