### ISSUE TITLE
[Bug]: Support Bundle shows "Error Processing Request"

### ISSUE THREAD

**Issue by realtofuine** [jumoog/intro-skipper#241]
### Self service debugging

- [x] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

The support bundle on Jellyfin native windows shows this:
![Screenshot 2024-08-08 at 10 24 14 AM](https://github.com/user-attachments/assets/38ffdae3-d59f-47b8-90d2-c3d1988cc169)

I'm not sure if chromaprint is enabled by default on ffmpeg because this is the native windows install. Also, the scheduled tasks are instantly failing.

### Jellyfin install method

Windows installer

### Container image/tag or Jellyfin version

10.9.9

### Operating System

Windows 11

### Support Bundle

```shell
Error processing request.
```

### Jellyfin logs

```shell
[2024-08-08 10:20:48.113 -05:00] [INF] [15] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Unstable plugin version built from commit "c0708528f0d22d61a20ae92a3c797e924162b1e2"
[2024-08-08 10:20:48.116 -05:00] [ERR] [15] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/IntroSkipper/SupportBundle".
System.Collections.Generic.KeyNotFoundException: The given key 'version' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.FormatFFmpegLog(String key)
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.GetChromaprintLogs()
   at ConfusedPolarBear.Plugin.IntroSkipper.Controllers.TroubleshootingController.GetSupportBundle()
   at lambda_method1072(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by AbandonedCart** [comment]
According to the log, it is failing to run the version command on ffmpeg. Do videos work normally?

**Comment by jumoog** [comment]
Its not a Plugin bug

**Comment by realtofuine** [comment]
Yeah, ffmpeg issue solved here: [https://github.com/jellyfin/jellyfin/issues/12411](https://github.com/jellyfin/jellyfin/issues/12411)
