### ISSUE TITLE
[Bug]: No files found while running tasks

### ISSUE THREAD

**Issue by luizkowalski** [jumoog/intro-skipper#248]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

Hey 👋🏻

When I try to run the tasks to detect intros or credits, they immediately fail:

```
[2024-08-18 13:00:56.035 +00:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros" Failed after 0 minute(s) and 0 seconds
[2024-08-18 13:00:57.468 +00:00] [INF] [42] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-08-18 13:00:57.653 +00:00] [INF] [42] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Series"
[2024-08-18 13:00:57.657 +00:00] [INF] [42] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Movies"
[2024-08-18 13:00:57.663 +00:00] [ERR] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze. If you are limiting the list of libraries to analyze, check that all library names have been spelled correctly.
   at ConfusedPolarBear.Plugin.IntroSkipper.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken, HashSet`1 seasonsToAnalyze)
   at ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-08-18 13:00:57.664 +00:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Failed after 0 minute(s) and 0 seconds
```

I do have episodes in Series library and this is how they are sorted:

```
└── Series
    ├── Parks.and.Recreation.S01.1080p.BluRay.x265-KONTRAST
    │   ├── Parks.and.Recreation.S01E01.1080p.BluRay.x265-KONTRAST.mp4
    │   ├── Parks.and.Recreation.S01E01.1080p.BluRay.x265-KONTRAST.pob.srt
    │   ├── Parks.and.Recreation.S01E02.1080p.BluRay.x265-KONTRAST.eng.srt
    │   ├── Parks.and.Recreation.S01E02.1080p.BluRay.x265-KONTRAST.mp4
    │   ├── Parks.and.Recreation.S01E03.1080p.BluRay.x265-KONTRAST.eng.srt
    │   ├── Parks.and.Recreation.S01E03.1080p.BluRay.x265-KONTRAST.mp4
    │   ├── Parks.and.Recreation.S01E04.1080p.BluRay.x265-KONTRAST.eng.sdh.srt
    │   ├── Parks.and.Recreation.S01E04.1080p.BluRay.x265-KONTRAST.mp4
    │   ├── Parks.and.Recreation.S01E05.1080p.BluRay.x265-KONTRAST.mp4
    │   ├── Parks.and.Recreation.S01E06.1080p.BluRay.x265-KONTRAST.eng.srt
    │   ├── Parks.and.Recreation.S01E06.1080p.BluRay.x265-KONTRAST.mp4
    │   └── Subs
    │       ├── Parks.and.Recreation.S01E01.1080p.BluRay.x265-KONTRAST
    │       │   ├── 3_eng,English.srt
    │       │   └── 4_eng,English SDH.srt
    │       ├── Parks.and.Recreation.S01E02.1080p.BluRay.x265-KONTRAST
....
```

This is how my Jellyfin was set up (I'm using Kamal, a Docker compose-like tool for deployments)

```
jellyfin:
  image: jellyfin/jellyfin:2024081205
  host: homeserver
  options:
    net: host
    device:
      - /dev/dri:/dev/dri
    group-add: 993
  directories:
    - /home/kowa/Media:/media
    - jellyfin/config:/config
    - jellyfin/cache:/cache
  labels:
    traefik.enable: false
```

Docker runs with a non-root user, part of `sudo` and `docker` groups

These are the folder permissions
```
drwxrwxr-x  3 kowa kowa   4096 Jul 27 11:50 homeserver-jellyfin/
```

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:2024081205

### Operating System

Ubuntu Server 24.04

### Support Bundle

```shell
* Jellyfin version: 10.10.0
* Plugin version: 0.2.0+92aa5fef8806
* Queue contents: 0 episodes, 0 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by luizkowalski** [comment]
Updated some library settings and it is working now!
