### ISSUE TITLE
[Bug]: Jellyfin API-Docs (api-docs/swagger/index.html) not rendering when plugin installed

### ISSUE THREAD

**Issue by Xameon42** [jumoog/intro-skipper#73]
### Describe the bug

Hello everybody,
today I noticed that the local Jellyfin API docs are not being rendered when this plugin is installed.
You get the following error message when calling /api-docs/swagger/index.html
```
Fetch error
Internal Server Error /api-docs/openapi.json
```
![screenshot](https://github.com/jumoog/intro-skipper/assets/142261328/0e061a41-9158-4dd7-b0bb-b2514db26f75)

The relevant Jellyfin log lines indicate that this is because no explicit HttpMethod is defined for a particular action.

I tested it with the latest pre-release version "intro-skipper-fd63670".

Apparently it is sufficient if the HTTP method is set for the action.
I tested this in a fork of the repo locally and the API documentation was loaded successfully again.

I will create a pull request for this.

If you also think that this is a bug, please feel free to merge it.
If you have any further questions, I will be happy to answer them.

### Jellyfin installation method

Installation over Jellyfin APT-Repository for Ubuntu

### Operating System

Ubuntu 22.04

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+fd636706cc4d
* Queue contents: 0 episodes, 0 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

### Jellyfin logs

```
[2024-03-10 19:19:36.895 +01:00] [ERR] [192] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/api-docs/openapi.json".
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - ConfusedPolarBear.Plugin.IntroSkipper.Controllers.SkipIntroController.GetUserInterfaceConfiguration (ConfusedPolarBear.Plugin.IntroSkipper). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by jumoog** [comment]
thanks alot!
